/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAside: typeof import('./src/components/BaseLayout/AppAside.vue')['default']
    AppHeader: typeof import('./src/components/BaseLayout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/BaseLayout/AppLayout.vue')['default']
    BaseCheckbox: typeof import('./src/components/BaseCheckbox/index.vue')['default']
    BaseCollapse: typeof import('./src/components/BaseCollapse/index.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog/index.vue')['default']
    BaseModel: typeof import('./src/components/BaseModel/index.vue')['default']
    BaseModelTurbine: typeof import('./src/components/BaseModelTurbine/index.vue')['default']
    BaseStackedLine: typeof import('./src/components/BaseStackedLine/index.vue')['default']
    BaseTable: typeof import('./src/components/BaseTable/index.vue')['default']
    BigScreen: typeof import('./src/components/BaseLayout/BigScreen.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetStackedLine: typeof import('./src/components/WidgetStackedLine/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
